export const state = {
  audioContext: null,
  isRunning: false,
  isPaused: false,
  isDraining: false,
  pausedWasDraining: false,
  pausedAt: null,
  seedMode: "seed",
  mode: "auto",
  ratioBias: "simple",
  notes: [],
  rafId: null,
  schedulerTimer: null,
  wakeLockSentinel: null,
  wakeLockRequestPending: false,
  startTime: performance.now() / 1000,
  timerEndTime: null,
  timerCompleted: false,
  nextEventTime: null,
  selectedNoteId: null,
  nextId: 1,
  lastGenerationNormalizeAt: -Infinity,
  namedCommaByVectorKey: new Map(),
  namedCommaIntervals: [],
  ratioPresets: [],
  selectedPresetId: "",
  lastTableRenderAt: -Infinity,
  currentLanguage: ["ja", "en"].includes(localStorage.getItem("rationalFlowLanguage"))
    ? localStorage.getItem("rationalFlowLanguage")
    : "ja",
  diesisBaseOctave: 5,
  diesisRatioDisplay: "ratio",
  diesisLimitFilter: Infinity,
  diesisShowDerived: true,
  diesisShowPower: true,
  diesisCollectionFilter: "all",
  discoveredDiesisCounts: new Map(),
  activeDiesisEncounterKeys: new Set(),
};
