export const state = {
  audioContext: null,
  isRunning: false,
  isPaused: false,
  isDraining: false,
  pausedWasDraining: false,
  pausedAt: null,
  workspaceMode: "play",
  seedMode: "seed",
  mode: "auto",
  ratioBias: "simple",
  notes: [],
  rafId: null,
  schedulerTimer: null,
  wakeLockSentinel: null,
  wakeLockRequestPending: false,
  startTime: performance.now() / 1000,
  timerEndTime: null,
  timerCompleted: false,
  nextEventTime: null,
  selectedNoteId: null,
  nextId: 1,
  lastGenerationNormalizeAt: -Infinity,
  namedCommaByVectorKey: new Map(),
  namedCommaIntervals: [],
  ratioPresets: [],
  selectedPresetId: "",
  lastTableRenderAt: -Infinity,
  currentLanguage: ["ja", "en"].includes(localStorage.getItem("rationalFlowLanguage"))
    ? localStorage.getItem("rationalFlowLanguage")
    : "ja",
  diesisBaseOctave: 5,
  diesisRatioDisplay: "ratio",
  diesisLimitFilter: Infinity,
  diesisDenominatorDigitsFilter: Infinity,
  diesisShowDerived: true,
  diesisShowPower: true,
  diesisCollectionFilter: "all",
  discoveredDiesisCounts: new Map(),
  activeDiesisEncounterKeys: new Set(),
  canvasPreviewPointerId: null,
  canvasPreviewLastNoteId: null,
  editor: {
    isLooping: false,
    isPaused: false,
    loopStartWallTime: null,
    pausedAtLoopTime: 0,
    playheadTime: 0,
    loopLength: 8,
    viewStart: 0,
    viewEnd: 8,
    defaultDuration: 2,
    timeSnap: 0.25,
    notes: [],
    selectedNoteIds: [],
    pairSelect: false,
    nextEditorId: 1,
    ratioSource: "partialGrid",
    singleRatioInput: "3/2",
    gridBase: 32,
    gridNumeratorMin: 33,
    gridNumeratorMax: 48,
    gridDirection: "both",
    drag: null,
    schedulerTimer: null,
    scheduledEvents: new Set(),
    playbackNotes: [],
  },
};
